name: test

on: 
  workflow_dispatch:
    inputs:
      environment_tag:
        description: 'Define env name'     
        required: true
        default: 'prod'
      branch:
        description: 'Define branch name'     
        required: true
        default: 'master'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Env: ${{ github.event.inputs.environment_tag }}" 
        echo "Branch: ${{ github.event.inputs.branch }}"        
